# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

sudo: required

dist: trusty

warnings_are_errors: true

r_build_args: --no-build-vignettes

r:
  - release
  - devel

os:
  - linux
  - osx

matrix:
  exclude:
    - os: osx
      r: devel

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

apt_packages:
  - libgdal-dev
  - libgeos-dev
  - libgeos-c1
  - libproj-dev
  - curl
  - qpdf 
  
before_install: 
  - echo "TRAVIS_OS_NAME = $TRAVIS_OS_NAME"
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then Rscript -e "install.packages(c('devtools'))"; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install Caskroom/cask/xquartz; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ghostscript; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then Rscript -e "setRepositories(ind=1:2);install.packages(c('rgdal','rgeos'))"; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo tlmgr update --self; fi;

r_packages:
  - covr
  - rmarkdown
  - testthat

after_success:
  - Rscript -e 'covr::codecov()' 

notifications:
  email:
    on_success: change
    on_failure: change
